# Generated by Django 5.2.8 on 2025-11-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_skill_options_remove_service_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfel',
            name='content',
        ),
    ]
