# Generated by Django 5.2.8 on 2025-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='author_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='position',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
