# Generated by Django 5.2.8 on 2025-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactmessage_author_email_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='category',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='author_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
